<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Roster Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Roster\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE SWAP — two cells, sent to the handset for acceptance.
 *
 * A NEW TABLE AND NOTHING TOUCHED, so there is nothing to expand, backfill
 * or contract. Both foreign keys into `roster_duty` cascade: an offer about
 * a watch that no longer exists is an offer about nothing.
 *
 * NO UNIQUE INDEX ON (duty, state). It would be the natural way to say "one
 * open offer per watch", and it is refused for a reason worth writing down:
 * Postgres treats a partial uniqueness like this as a job for a PARTIAL
 * index, and a plain unique on the pair would forbid a second DECLINED offer
 * on the same watch too — which is exactly the case the design needs, since
 * asking a second person after the first said no is the ordinary way a hole
 * gets filled. The one-open-offer rule is enforced in
 * {@see \Uhifadhi\Roster\Service\SwapService::offer()} where it can say so.
 */
final class Version20260920000200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'A swap: two cells, offered and answered on the handset';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE roster_swap (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, state VARCHAR(16) NOT NULL, responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, note VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, duty_id INT NOT NULL, counter_duty_id INT DEFAULT NULL, offered_to_id INT NOT NULL, offered_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2DE1A8B6D17F50A6 ON roster_swap (uuid)');
        $this->addSql('CREATE INDEX idx_roster_swap_area_state ON roster_swap (area_id, state)');
        $this->addSql('CREATE INDEX IDX_2DE1A8B6BD0F409C ON roster_swap (area_id)');
        $this->addSql('CREATE INDEX IDX_2DE1A8B63A1F9EC1 ON roster_swap (duty_id)');
        $this->addSql('CREATE INDEX IDX_2DE1A8B6B474C2E0 ON roster_swap (counter_duty_id)');
        $this->addSql('CREATE INDEX IDX_2DE1A8B65C5F396E ON roster_swap (offered_to_id)');
        $this->addSql('CREATE INDEX IDX_2DE1A8B6C68D530F ON roster_swap (offered_by_id)');
        $this->addSql('ALTER TABLE roster_swap ADD CONSTRAINT FK_2DE1A8B6BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_swap ADD CONSTRAINT FK_2DE1A8B63A1F9EC1 FOREIGN KEY (duty_id) REFERENCES roster_duty (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_swap ADD CONSTRAINT FK_2DE1A8B6B474C2E0 FOREIGN KEY (counter_duty_id) REFERENCES roster_duty (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_swap ADD CONSTRAINT FK_2DE1A8B65C5F396E FOREIGN KEY (offered_to_id) REFERENCES team_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_swap ADD CONSTRAINT FK_2DE1A8B6C68D530F FOREIGN KEY (offered_by_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS roster_swap CASCADE');
    }
}
