<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Roster Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Roster\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * HOW ONE PERSON LIKES THE SHEET — the weeks they read at a time, and
 * the stations they keep folded.
 *
 * ONE ROW PER PERSON PER AREA, written the first time somebody expresses
 * a preference. Nobody has one today and nobody needs one: the standard
 * is two weeks and every station open, which is what a missing row
 * means, so there is nothing to backfill.
 *
 * OPEN IS THE DEFAULT AND CLOSED IS WHAT IS STORED, which is why the
 * column is the folded list and not the open one: a station added to the
 * area tomorrow is open tomorrow, rather than hidden by a preference
 * written before it existed.
 */
final class Version20260921000300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'How one person likes the sheet: the weeks, and the folds.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE roster_sheet_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, weeks INT NOT NULL, folded JSON NOT NULL, person_id INT NOT NULL, area_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_roster_sheet_preference_person_area ON roster_sheet_preference (person_id, area_id)');
        $this->addSql('CREATE INDEX IDX_D2A1EF91217BBB47 ON roster_sheet_preference (person_id)');
        $this->addSql('CREATE INDEX IDX_D2A1EF91BD0F409C ON roster_sheet_preference (area_id)');
        $this->addSql('ALTER TABLE roster_sheet_preference ADD CONSTRAINT fk_roster_sheet_preference_person FOREIGN KEY (person_id) REFERENCES team_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_sheet_preference ADD CONSTRAINT fk_roster_sheet_preference_area FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    /** One table created; dropping it in `down()` is the reverse and not a release. */
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS roster_sheet_preference');
    }
}
