<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Roster Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Roster\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE MODULE'S FIRST TABLES — the shift vocabulary an area edits, the standing
 * rotations and their ordered pools, the duties a rotation generates, the days
 * a person has edited, and the absences that make holes.
 *
 * ORDER IS THE COMPOSER GRAPH, NOT THE CLOCK. The cross-package foreign keys
 * here point at `area_of_interest`, `station` and `team_user`, all of them the
 * core's — and the core's versions run first because this package requires it,
 * whatever the dates on the two files say.
 *
 * NOTHING TO EXPAND OR BACKFILL: every table is new, so there is no row for a
 * NOT NULL column to be wrong about. The expand/backfill/contract discipline
 * starts with the second migration.
 */
final class Version20260920000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Shifts, rotations and their pools, duties, edited days and absences';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE roster_rotation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, scope VARCHAR(16) NOT NULL, team_name VARCHAR(96) DEFAULT NULL, cycle JSON NOT NULL, anchored_on DATE NOT NULL, slots_per_shift JSON NOT NULL, stand_down_weekdays JSON NOT NULL, rest_rule VARCHAR(32) NOT NULL, horizon_days INT NOT NULL, generated_through DATE DEFAULT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, station_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B1B85F24D17F50A6 ON roster_rotation (uuid)');
        $this->addSql('CREATE INDEX IDX_B1B85F24BD0F409C ON roster_rotation (area_id)');
        $this->addSql('CREATE INDEX IDX_B1B85F2421BDB235 ON roster_rotation (station_id)');
        $this->addSql('CREATE TABLE roster_edited_day (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, on_day DATE NOT NULL, edited_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, station_id INT NOT NULL, edited_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_roster_edited_day_station_day ON roster_edited_day (station_id, on_day)');
        $this->addSql('CREATE INDEX IDX_460366DD21BDB235 ON roster_edited_day (station_id)');
        $this->addSql('CREATE INDEX IDX_460366DDDD7B2EBC ON roster_edited_day (edited_by_id)');
        $this->addSql('CREATE TABLE roster_shift (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, shift_key VARCHAR(32) NOT NULL, label VARCHAR(64) NOT NULL, starts_at VARCHAR(5) NOT NULL, ends_at VARCHAR(5) NOT NULL, position INT NOT NULL, closed_at DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BDB40E1FD17F50A6 ON roster_shift (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_roster_shift_area_key ON roster_shift (area_id, shift_key)');
        $this->addSql('CREATE INDEX IDX_BDB40E1FBD0F409C ON roster_shift (area_id)');
        $this->addSql('CREATE TABLE roster_absence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, starts_on DATE NOT NULL, ends_on DATE NOT NULL, kind VARCHAR(16) NOT NULL, note VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, person_id INT NOT NULL, recorded_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_60BD898BD17F50A6 ON roster_absence (uuid)');
        $this->addSql('CREATE INDEX idx_roster_absence_person_span ON roster_absence (person_id, starts_on, ends_on)');
        $this->addSql('CREATE INDEX IDX_60BD898BBD0F409C ON roster_absence (area_id)');
        $this->addSql('CREATE INDEX IDX_60BD898B217BBB47 ON roster_absence (person_id)');
        $this->addSql('CREATE INDEX IDX_60BD898BD05A957B ON roster_absence (recorded_by_id)');
        $this->addSql('CREATE TABLE roster_rotation_pool (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, rotation_id INT NOT NULL, person_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_roster_pool_rotation_person ON roster_rotation_pool (rotation_id, person_id)');
        $this->addSql('CREATE INDEX IDX_63087FFC326CE1FB ON roster_rotation_pool (rotation_id)');
        $this->addSql('CREATE INDEX IDX_63087FFC217BBB47 ON roster_rotation_pool (person_id)');
        $this->addSql('CREATE TABLE roster_duty (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, shift_key VARCHAR(32) NOT NULL, on_day DATE NOT NULL, state VARCHAR(16) NOT NULL, note VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, station_id INT NOT NULL, rotation_id INT DEFAULT NULL, person_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ADC24D4ED17F50A6 ON roster_duty (uuid)');
        $this->addSql('CREATE INDEX idx_roster_duty_area_day ON roster_duty (area_id, on_day)');
        $this->addSql('CREATE INDEX idx_roster_duty_station_day ON roster_duty (station_id, on_day)');
        $this->addSql('CREATE INDEX idx_roster_duty_person_day ON roster_duty (person_id, on_day)');
        $this->addSql('CREATE UNIQUE INDEX uniq_roster_duty_person_station_shift_day ON roster_duty (person_id, station_id, shift_key, on_day)');
        $this->addSql('CREATE INDEX IDX_ADC24D4EBD0F409C ON roster_duty (area_id)');
        $this->addSql('CREATE INDEX IDX_ADC24D4E21BDB235 ON roster_duty (station_id)');
        $this->addSql('CREATE INDEX IDX_ADC24D4E326CE1FB ON roster_duty (rotation_id)');
        $this->addSql('CREATE INDEX IDX_ADC24D4E217BBB47 ON roster_duty (person_id)');
        $this->addSql('ALTER TABLE roster_rotation ADD CONSTRAINT FK_B1B85F24BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_rotation ADD CONSTRAINT FK_B1B85F2421BDB235 FOREIGN KEY (station_id) REFERENCES station (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_edited_day ADD CONSTRAINT FK_460366DD21BDB235 FOREIGN KEY (station_id) REFERENCES station (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_edited_day ADD CONSTRAINT FK_460366DDDD7B2EBC FOREIGN KEY (edited_by_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_shift ADD CONSTRAINT FK_BDB40E1FBD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_absence ADD CONSTRAINT FK_60BD898BBD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_absence ADD CONSTRAINT FK_60BD898B217BBB47 FOREIGN KEY (person_id) REFERENCES team_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_absence ADD CONSTRAINT FK_60BD898BD05A957B FOREIGN KEY (recorded_by_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_rotation_pool ADD CONSTRAINT FK_63087FFC326CE1FB FOREIGN KEY (rotation_id) REFERENCES roster_rotation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_rotation_pool ADD CONSTRAINT FK_63087FFC217BBB47 FOREIGN KEY (person_id) REFERENCES team_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_duty ADD CONSTRAINT FK_ADC24D4EBD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_duty ADD CONSTRAINT FK_ADC24D4E21BDB235 FOREIGN KEY (station_id) REFERENCES station (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_duty ADD CONSTRAINT FK_ADC24D4E326CE1FB FOREIGN KEY (rotation_id) REFERENCES roster_rotation (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE roster_duty ADD CONSTRAINT FK_ADC24D4E217BBB47 FOREIGN KEY (person_id) REFERENCES team_user (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // CASCADE because the tables reference each other and the core's; the
        // core's own tables are untouched, which is what a module's down() is
        // allowed to promise.
        $this->addSql('DROP TABLE IF EXISTS roster_duty CASCADE');
        $this->addSql('DROP TABLE IF EXISTS roster_rotation_pool CASCADE');
        $this->addSql('DROP TABLE IF EXISTS roster_absence CASCADE');
        $this->addSql('DROP TABLE IF EXISTS roster_edited_day CASCADE');
        $this->addSql('DROP TABLE IF EXISTS roster_shift CASCADE');
        $this->addSql('DROP TABLE IF EXISTS roster_rotation CASCADE');
    }
}
